env = "local"

[es]
    addrs = ["http://127.0.0.1:9200"]

[redis]
    [redis.master]
        host = "localhost"
        port = 6379
        password = ""
        database = 0
    [redis.activity]
        host = "localhost"
        port = 6379
        password = ""
        database = 0

[mysql]
    [mysql.master]
        name = "rem"
        port = 3306
        host = "127.0.0.1"
        user = "root"
        password = "root"
        charset = "utf8mb4"
        maxIdleConnection = 100
        maxOpenConnection = 100
        connMaxLifetime = 30
    [mysql.slave]
        name = "rem"
        port = 3306
        host = "127.0.0.1"
        user = "root"
        password = "root"
        charset = "utf8mb4"
        maxIdleConnection = 100
        maxOpenConnection = 100
        connMaxLifetime = 30
    [mysql.s_master]
        name = "rem_statistics"
        port = 3306
        host = "127.0.0.1"
        user = "root"
        password = "root"
        charset = "utf8mb4"
        maxIdleConnection = 100
        maxOpenConnection = 100
        connMaxLifetime = 30
    [mysql.s_slave]
        name = "rem_statistics"
        port = 3306
        host = "127.0.0.1"
        user = "root"
        password = "root"
        charset = "utf8mb4"
        maxIdleConnection = 100
        maxOpenConnection = 100
        connMaxLifetime = 30

[mongodb]
    uri = "mongodb://localhost:27017"
    replicaSet = ""
    readPreference = 2


[logger]
    file = "./local.log"